apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flask
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: default
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: asia-east1-docker.pkg.dev/no-org-329603/flask-api-repo/flask-app_api:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP


