version: "3.9"
services:
  flask:
    build: ./api
    container_name: flask_api
    restart: always
    expose: 
      - 80
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
